---
log_base_dir: logs/BJ_GM
log_level: INFO

data:
  batch_size: 32
  dataset_dir: data/BJ_GM
  val_batch_size: 32
  graph_pkl_filename: data/sensor_graph/adj_GM.npy

model:
  l1_decay: 0
  seq_len: 12
  horizon: 12
  input_dim: 1 
  output_dim: 1
  latent_dim: 4
  n_traj_samples: 3
  ode_method: dopri5 
  odeint_atol: 0.00001 
  odeint_rtol: 0.00001 
  rnn_units: 64 
  num_rnn_layers: 1
  gcn_step: 2
  filter_type: default # unkP IncP default
  recg_type: gru 
  save_latent: false
  nfe: false

train:
  base_lr: 0.01
  dropout: 0
  load: 0 
  epoch: 0 
  epochs: 100
  epsilon: 1.0e-3
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 20
  steps: [20, 30, 40, 50]
  test_every_n_epochs: 5
  